"use client";
import { useEffect, useState } from "react";
import { useParams, useRouter } from "next/navigation";

export default function ExecutiveLeadDetail() {
  const { id } = useParams(); const router = useRouter(); const [lead, setLead] = useState<any>(); const [error, setError] = useState("");
  useEffect(() => { fetch(`/api/leads/${id}`).then(async r => { if (!r.ok) throw new Error(); return r.json(); }).then(value => setLead(value.lead)).catch(() => setError("This assigned lead is unavailable.")); }, [id]);
  if (error) return <p className="text-rose-400">{error}</p>; if (!lead) return <p className="text-slate-400">Loading lead…</p>;
  return <div className="mx-auto max-w-3xl space-y-5"><button onClick={() => router.back()} className="text-sm text-slate-400">← Back to My Leads</button><section className="rounded-2xl border border-indigo-500/30 bg-[#12141C] p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold text-indigo-300">READ ONLY LEAD RECORD</p><h1 className="mt-1 text-2xl font-bold">{lead.businessName}</h1><p className="mt-1 text-sm text-slate-400">{lead.category} · {lead.source}</p></div><span className="rounded-full border border-slate-600 px-3 py-1 text-xs text-slate-300">Locked master details</span></div><div className="mt-5 grid gap-3 rounded-xl border border-[#1E2333] p-4 sm:grid-cols-2"><p><span className="text-xs text-slate-400">Phone</span><br/>{lead.phone}</p><p><span className="text-xs text-slate-400">Location</span><br/>{[lead.area,lead.city,lead.state].filter(Boolean).join(", ")||"Not available"}</p><p><span className="text-xs text-slate-400">Last call status</span><br/>{lead.lastCallOutcome||lead.status}</p><p><span className="text-xs text-slate-400">Next follow-up</span><br/>{lead.nextFollowUpDate?new Date(lead.nextFollowUpDate).toLocaleString():"None scheduled"}</p></div><div className="mt-5 flex gap-3"><a href={`tel:${lead.phone}`} className="rounded-lg bg-white px-4 py-2 font-bold text-black">Call</a><a target="_blank" href={`https://wa.me/${lead.normalizedPhone}`} className="rounded-lg border border-emerald-500/50 px-4 py-2 font-bold text-emerald-300">WhatsApp</a></div></section><section className="rounded-2xl border border-[#1E2333] bg-[#12141C] p-5"><h2 className="font-bold">Previous Notes & Call History</h2><div className="mt-3 space-y-3">{lead.calls.length?lead.calls.map((call:any)=><div className="rounded-lg bg-[#0D0F17] p-3 text-sm" key={call.id}><b>{call.outcome.replaceAll("_"," ")}</b><p className="mt-1 text-slate-400">{call.clientConversationSummary||call.notes||"No summary"}</p></div>):<p className="text-sm text-slate-400">No calls logged yet.</p>}</div></section></div>;
}
